name: Setup IaC tools
description: Install Terraform and Terragrunt for deployment jobs.
runs:
  using: composite
  steps:
    - name: Setup Terraform and Terragrunt
      uses: gruntwork-io/terragrunt-action@4ed5b7344c80315e5357f28f36159fc980bc2d5a # v3.4.0
