terraform {
  required_version = ">= 1.15"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}

# The default aws provider (ap-northeast-1) is generated by the root.hcl.
# Only the us-east-1 aliased provider is declared here, required for ACM
# certificates used with CloudFront.
provider "aws" {
  alias  = "us_east_1"
  region = "us-east-1"
}
